INSERT INTO clients(client_name, email, phone_number) VALUES ("Emily Johnson", "emily@test.com", 123456789)
INSERT INTO clients(client_name, email, phone_number) VALUES ("Liam Smith", "liam.smith@test.com", 234567891);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Olivia Brown", "olivia.brown@test.com", 345678912);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Noah Davis", "noah.davis@test.com", 456789123);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Emma Wilson", "emma.wilson@test.com", 567891234);
INSERT INTO clients(client_name, email, phone_number) VALUES ("James Taylor", "james.taylor@test.com", 678912345);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Sophia Anderson", "sophia.anderson@test.com", 789123456);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Benjamin Thomas", "benjamin.thomas@test.com", 891234567);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Amelia Jackson", "amelia.jackson@test.com", 912345678);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Elijah White", "elijah.white@test.com", 123456780);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Isabella Harris", "isabella.harris@test.com", 234567890);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Lucas Martin", "lucas.martin@test.com", 345678901);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Mia Thompson", "mia.thompson@test.com", 456789012);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Henry Garcia", "henry.garcia@test.com", 567890123);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Charlotte Martinez", "charlotte.martinez@test.com", 678901234);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Alexander Rodriguez", "alexander.rodriguez@test.com", 789012345);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Evelyn Lewis", "evelyn.lewis@test.com", 890123456);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Michael Lee", "michael.lee@test.com", 901234567);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Abigail Walker", "abigail.walker@test.com", 123450987);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Daniel Hall", "daniel.hall@test.com", 234560987);
INSERT INTO clients(client_name, email, phone_number) VALUES ("Ava Young", "ava.young@test.com", 345670987);



INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Necklace", 1, "Red", "2023-09-01", "Satin", "2023-08-01", "Dress", "M", "In Progress", 120.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Necklace", 1, "Red", "2023-10-30", "Satin", "2023-08-01", "Dress", "M", "In Progress", 120.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Earrings", 2, "Blue", "2023-09-05", "Chiffon", "2023-08-03", "Gown", "S", "Completed", 140.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bracelet", 3, "Green", "2023-09-08", "Cotton", "2023-08-04", "Shirt", "L", "In Progress", 75.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Scarf", 4, "Black", "2023-09-10", "Silk", "2023-08-05", "Blouse", "M", "Cancelled", 95.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Belt", 5, "White", "2023-09-15", "Linen", "2023-08-07", "Pants", "XL", "Completed", 110.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Necklace", 6, "Yellow", "2023-09-18", "Polyester", "2023-08-08", "Jacket", "S", "In Progress", 150.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Hat", 7, "Purple", "2023-09-20", "Denim", "2023-08-10", "Skirt", "M", "Completed", 85.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Ring", 8, "Pink", "2023-09-22", "Velvet", "2023-08-12", "Coat", "L", "In Progress", 130.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Brooch", 9, "Orange", "2023-09-25", "Wool", "2023-08-13", "Sweater", "M", "Completed", 100.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Sunglasses", 10, "Navy", "2023-09-28", "Leather", "2023-08-15", "Dress", "S", "Cancelled", 165.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Gloves", 11, "Teal", "2023-10-01", "Silk", "2023-08-18", "Gown", "M", "In Progress", 155.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bag", 12, "Gray", "2023-10-05", "Linen", "2023-08-19", "Blouse", "L", "Completed", 120.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Watch", 13, "Cyan", "2023-10-08", "Polyester", "2023-08-22", "Shirt", "S", "In Progress", 135.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bow", 14, "Maroon", "2023-10-10", "Cotton", "2023-08-24", "Pants", "M", "Completed", 105.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Tie", 15, "Olive", "2023-10-12", "Chiffon", "2023-08-26", "Jacket", "XL", "In Progress", 140.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Hairpin", 16, "Mint", "2023-10-15", "Velvet", "2023-08-28", "Skirt", "S", "Completed", 90.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Pendant", 17, "Lavender", "2023-10-20", "Satin", "2023-08-30", "Coat", "L", "In Progress", 150.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Anklet", 18, "Coral", "2023-10-22", "Denim", "2023-09-01", "Sweater", "M", "Completed", 115.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bracelet", 19, "Turquoise", "2023-10-25", "Wool", "2023-09-02", "Dress", "XL", "In Progress", 175.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Belt", 20, "Beige", "2023-10-28", "Leather", "2023-09-03", "Gown", "S", "Cancelled", 160.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Scarf", 1, "Red", "2023-10-30", "Chiffon", "2023-09-04", "Blouse", "M", "In Progress", 130.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Necklace", 2, "Blue", "2023-10-31", "Silk", "2023-09-05", "Shirt", "S", "Completed", 145.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Hat", 3, "Green", "2023-11-01", "Velvet", "2023-09-06", "Coat", "L", "In Progress", 135.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Ring", 4, "Orange", "2023-11-03", "Chiffon", "2023-09-07", "Gown", "M", "Completed", 175.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Watch", 5, "Black", "2023-11-05", "Wool", "2023-09-08", "Pants", "XL", "In Progress", 165.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Belt", 6, "Yellow", "2023-11-06", "Polyester", "2023-09-09", "Blouse", "S", "Completed", 155.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Scarf", 7, "Purple", "2023-11-08", "Satin", "2023-09-10", "Jacket", "M", "In Progress", 125.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Tie", 8, "Pink", "2023-11-10", "Denim", "2023-09-11", "Shirt", "L", "Cancelled", 180.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bracelet", 9, "Lavender", "2023-11-12", "Chiffon", "2023-09-12", "Skirt", "S", "Completed", 155.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bow", 10, "Navy", "2023-11-15", "Leather", "2023-09-14", "Dress", "M", "In Progress", 140.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Brooch", 11, "Mint", "2023-11-18", "Satin", "2023-09-16", "Gown", "XL", "Completed", 135.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Pendant", 12, "Coral", "2023-11-20", "Velvet", "2023-09-17", "Sweater", "L", "Cancelled", 160.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Hat", 13, "Gray", "2023-11-23", "Wool", "2023-09-18", "Coat", "S", "In Progress", 155.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Gloves", 14, "Cyan", "2023-11-26", "Polyester", "2023-09-19", "Blouse", "M", "Completed", 145.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bag", 15, "Maroon", "2023-11-28", "Silk", "2023-09-20", "Dress", "L", "Cancelled", 170.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bracelet", 16, "Turquoise", "2023-11-30", "Cotton", "2023-09-22", "Pants", "S", "In Progress", 185.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Scarf", 17, "Lavender", "2023-12-02", "Denim", "2023-09-24", "Gown", "M", "Completed", 130.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Tie", 18, "Beige", "2023-12-05", "Wool", "2023-09-26", "Jacket", "L", "Cancelled", 160.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Anklet", 19, "Teal", "2023-12-08", "Satin", "2023-09-28", "Shirt", "XL", "Completed", 145.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Earrings", 20, "Gray", "2023-12-10", "Polyester", "2023-10-01", "Coat", "S", "In Progress", 155.5);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Bow", 1, "Mint", "2023-12-13", "Velvet", "2023-10-03", "Sweater", "M", "Completed", 125.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Brooch", 2, "Olive", "2023-12-15", "Chiffon", "2023-10-05", "Shirt", "L", "Cancelled", 165.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Pendant", 3, "Yellow", "2023-12-18", "Silk", "2023-10-07", "Dress", "XL", "In Progress", 145.0);
INSERT INTO orders (accessories, client_id, color, estimated_delivery_date, fabric_type, order_date, outfit_type, size, status, total_price) VALUES ("Necklace", 4, "Coral", "2023-12-21", "Cotton", "2023-10-10", "Skirt", "S", "Completed", 175.5);
